ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('accounts.urls')),
    path('shop/', include('products.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),

    path('search/', views.search, name='search'),
    path('subscribe-to-newsletter/', views.subscribe_to_newsletter, name='subscribe_to_newsletter'),

    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
]

products/urls.py
from django.urls import path
from . import views, forms

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='all_products'),

    path('product/<str:short_name>', views.view_product_details, name='view_product_details'),

    path('collections/', views.collections, name='collections'),
    path('collections/<str:collection>', views.collection_view, name='collection_view'),

    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('order-complete/', views.order_complete, name='order_complete'),

    path('wishlist/', views.wishlist, name='wishlist'),

    # forms
    path('use-coupon/', forms.use_coupon, name='use_coupon'),
    path('process-checkout/', forms.process_checkout, name='process_checkout'),

    path('add-review/', forms.add_review, name='add_review'),

    path('add-to-wishlist/', forms.add_to_wishlist, name='add_to_wishlist'),
    path('remove-wishlist-item/', forms.remove_item_from_wishlist, name='remove_item_from_wishlist'),

    path('add-to-cart/', forms.add_to_cart, name='add_to_cart'),
    path('items-in-cart-count/', forms.get_number_of_cart_items, name='get_number_of_cart_items'),
    path('update-cart-data/', forms.update_cart_data, name='update_cart_data'),
    path('clear-cart-items/', forms.clear_cart_items, name='clear_cart_items'),
    path('get-cart-items/', forms.get_cart_items, name='get_cart_items'),
    path('remove-cart-item/', forms.remove_item_from_cart, name='remove_item_from_cart'),

]

products/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Users


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255, default='')
    in_stock = models.PositiveIntegerField(default=0)
    colors_available = models.CharField(max_length=255, default='')
    sizes_available = models.CharField(max_length=255, default='')

    description = models.TextField(default='')
    has_discount = models.BooleanField(default='')
    discounted_percent = models.PositiveIntegerField(default=0)
    is_new = models.BooleanField(default=True)

    price = models.PositiveIntegerField(default=0)
    sales_count = models.PositiveIntegerField(default=0)
    category = models.CharField(max_length=255, default='clothing')

    def __str__(self):
        return self.name

    def get_short_name(self):
        return self.name.lower().replace(' ', '')


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file = models.FileField()

    def __str__(self):
        return self.product.name


class Cart(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=5, default='')
    color = models.CharField(max_length=255, default='')

    def __str__(self):
        return f'{self.user} - {self.product}'


class Wishlist(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.product}'


class Orders(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=255, default='')
    address = models.CharField(max_length=255, default='')
    city = models.CharField(max_length=255, default='')
    post_code = models.CharField(max_length=255, default='')
    state = models.CharField(max_length=255, default='')
    country = models.CharField(max_length=255, default='')
    order_notes = models.TextField(default='')
    total_price = models.CharField(max_length=255, default='')
    status = models.CharField(max_length=255, default='pending')

    def __str__(self):
        return self.user.email


class OrderItems(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.order.user.email}: Order-{self.order.id}'


class RecentlyViewedProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=255, default='')


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default='')
    email = models.EmailField(max_length=255, default='')
    title = models.CharField(max_length=255, default='')
    body = models.TextField(default='')
    rating = models.PositiveIntegerField(default=0)
    review_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

products/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect

from .models import *
from .reuseable_functions import *


# Create your views here.
def all_products(request):
    products = []
    all_shop_products = get_all_products(include_out_of_stock=True)
    popular_products = get_best_selling_products(include_out_of_stock=False, order='descending')[:4]

    # if the user only wants products on sale
    if request.GET.get('on-sale'):
        all_shop_products = get_on_sale_products(include_out_of_stock=True)

    # if the user wants the products sorted a particular way
    if request.GET.get('sort'):
        sort = request.GET.get('sort')
        if sort == 'a-z':
            all_shop_products = sorted(all_shop_products, key=lambda x: x['name'])
        elif sort == 'z-a':
            all_shop_products = sorted(all_shop_products, key=lambda x: x['name'], reverse=True)
        elif sort == 'price-high-price-low':
            all_shop_products = sorted(all_shop_products, key=lambda x: x['price'], reverse=True)
        elif sort == 'price-low-price-high':
            all_shop_products = sorted(all_shop_products, key=lambda x: x['price'])
        elif sort == 'best-selling':
            all_shop_products = sorted(all_shop_products, key=lambda x: x['sales_count'])

    for product in all_shop_products:

        # if the user only wants products of a particular proce range
        if request.GET.get('price'):
            price_range = request.GET.get('price').replace('%24', '').split('-')
            min_price = int(price_range[0].strip('+$ '))
            max_price = int(price_range[1].strip('+$ ')) + 1

            if product['price'] not in range(min_price, max_price) and product['slashed_price'] not in range(
                    min_price, max_price):
                continue

        # if user only wants products of specific category
        if request.GET.get('category'):
            if product['category'] == request.GET.get('category'):
                products.append(product)
        else:
            products.append(product)

    data = {'products': products, 'popular_products': popular_products, 'products_length': len(products)}
    return render(request, 'products/shop.html', data)


def collections(request):
    return render(request, 'products/collections.html')


def collection_view(request, collection):
    return redirect(f'/shop?category={collection}')


def view_product_details(request, short_name):
    """
    The product view page is gotten by its name stripped of spaces and set to lower letters. a function was created in
    the model to convert this format. if the name gotten from the url matches any product name, then the necessary data
    for the page is sorted into a simple format. Firstly, the discounts, colors and sizes are all set. Then the
    individual as well as total product reviews are also set. The sessions key is set and retrieved in order to fill in
    data for the recenlty viewed model
    :param request:
    :param short_name:
    :return:
    """
    products = Product.objects.all()
    suggested_products = get_suggested_products(request.session.session_key)

    for product in products:
        if product.get_short_name() == short_name:
            slashed_price = product.price - round(product.price * (product.discounted_percent / 100))
            colors_available = json.loads(str(product.colors_available).strip("' ").replace('\'', '\"'))
            sizes_available = json.loads(str(product.sizes_available).strip("' ").replace('\'', '\"'))

            reviews = get_all_product_reviews(product)
            total_reviews = get_all_product_reviews_ratings(product)
            review_count = len(reviews)

            # if a user isn't logged in, there is no session key. So for non-logged-in users a session key is created
            # for the recently viewed model
            if not request.session.exists(request.session.session_key):
                request.session.create()

            session_key = request.session.session_key

            product_data = {
                'pk': product.id,
                'first_image': product.productimage_set.all()[0].file,
                'all_product_images': product.productimage_set.all(),
                'name': product.name,
                'short_name': product.get_short_name(),
                'price': product.price,
                'in_stock': product.in_stock,
                'out_of_stock': True if product.in_stock == 0 else False,
                'first_color': colors_available[0],
                'colors_available': colors_available,
                'first_size': sizes_available[0],
                'sizes_available': sizes_available,
                'description': product.description,
                'has_discount': product.has_discount,
                'is_new': product.is_new,
                'discounted_percent': product.discounted_percent,
                'slashed_price': round(slashed_price, 2),
                'saved_amount': round(product.price - slashed_price, 2),
            }

            # adding the product to the list of recently viewed products for the session
            already_viewed_count = RecentlyViewedProduct.objects.filter(product=product,
                                                                        session_key=session_key).count()
            if already_viewed_count == 0:
                new_recently_viewed_product = RecentlyViewedProduct(session_key=session_key,
                                                                    product=product)
                new_recently_viewed_product.save()

            recently_viewed_items = []

            # retrieving all recently viewed products
            for viewed_product in RecentlyViewedProduct.objects.filter(session_key=session_key).all():
                item = {
                    'name': viewed_product.product.name,
                    'short_name': viewed_product.product.get_short_name(),
                    'first_image': viewed_product.product.productimage_set.all()[0].file,
                    'second_image': viewed_product.product.productimage_set.all()[1].file,
                    'has_discount': viewed_product.product.has_discount,
                    'is_new': viewed_product.product.is_new,
                    'discounted_percent': viewed_product.product.discounted_percent,
                }

                recently_viewed_items.append(item)

            data = {
                'product_data': product_data,
                'recently_viewed_items': recently_viewed_items,
                'suggested_products': suggested_products,
                'reviews': reviews,
                'total_reviews': total_reviews,
                'has_reviews': True if review_count != 0 else False,
                'review_count': review_count
            }
            return render(request, 'products/product_detail.html', data)
    raise Http404


@login_required(login_url='/auth/login/')
def cart(request):
    cart_items = get_all_cart_items(request.user)
    subtotal = sum(item['total_price'] for item in cart_items)
    return render(request, 'products/cart.html', {'cart_items': cart_items, 'subtotal': subtotal})


@login_required(login_url='/auth/login/')
def wishlist(request):
    all_wishlist_items = Wishlist.objects.filter(user=request.user).all()
    wishlist_items = []

    for item in all_wishlist_items:
        if item.product.has_discount:
            price = item.product.price - round(item.product.price * (item.product.discounted_percent / 100))
        else:
            price = item.product.price

        data = {
            'pk': item.id,
            'name': item.product.name,
            'image': item.product.productimage_set.all()[0].file,
            'short_name': item.product.get_short_name(),
            'price': price,
            'stock': 'out of stock' if item.product.in_stock == 0 else 'in stock',
        }
        wishlist_items.append(data)
    return render(request, 'products/wishlist.html', {'wishlist_items': wishlist_items})


@login_required(login_url='/auth/login/')
def checkout(request):
    cart_items = get_all_cart_items(request.user)
    subtotal = sum(item['total_price'] for item in cart_items)
    shipping_fee = round(subtotal * 0.12)  # this is set to 0 if worldwide shipping is free
    sum_total = subtotal + shipping_fee

    data = {'cart_items': cart_items, 'subtotal': subtotal, 'shipping_fee': shipping_fee, 'sum_total': sum_total}
    return render(request, 'products/checkout.html', data)


def orders(request):
    all_orders = request.user.orders_set.all()
    order_items = []

    if all_orders:
        for order in all_orders:
            all_order_items = order.orderitems_set.all()
            for order_item in all_order_items:
                item = {
                    'name': order_item.product.name,
                    'image': order_item.product.productimage_set.all()[0].file,
                    'short_name': order_item.product.get_short_name(),
                    'price': order_item.product.price,
                    'status': order.status,
                }
                order_items.append(item)
    return render(request, 'products/orders.html', {'order_items': order_items})


def order_complete(request):
    return render(request, 'products/order_complete.html')

products/templates/products/cart.html
{% extends 'main/base.html' %} 
{% load static %} 

{% block title %}CART{% endblock %} 

{% block content %}
<!--Page Title-->
<div class="page section-header text-center">
  <div class="page-title">
    <div class="wrapper"><h1 class="page-width">Your Cart</h1></div>
  </div>
</div>
<!--End Page Title-->

<div class="container pb-5">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-8 col-lg-8 main-col">
      <form action="{% url 'products:update_cart_data' %}" method="post" class="cart style2">
        {% csrf_token %}
        <table>
          <thead class="cart__row cart__header">
            <tr>
              <th colspan="2" class="text-center">Product</th>
              <th class="text-center">Price</th>
              <th class="text-center">Quantity</th>
              <th class="text-right">Total</th>
              <th class="action">&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            {% if cart_items %}
            {% for item in cart_items %}
            <tr class="cart__row border-bottom line1 cart-flex border-top">
              <td class="cart__image-wrapper cart-flex-item">
                <a href="{% url 'products:view_product_details' short_name=item.short_name %}" >
                    <img
                    class="cart__image"
                    src="{% static '' %}media/{{ item.image }}"
                    alt="Elastic Waist Dress - Navy / Small"
                /></a>
              </td>
              <td class="cart__meta small--text-left cart-flex-item">
                <div class="list-view-item__title">
                  <a href="{% url 'products:view_product_details' short_name=item.short_name %}">Elastic Waist Dress </a>
                </div>

                <div class="cart__meta-text">
                  Color: {{ item.color }}<br />Size: {{ item.size }}<br />
                </div>
              </td>
              <td class="cart__price-wrapper cart-flex-item">
                <span class="money">${{ item.price }}</span>
              </td>
              <td class="cart__update-wrapper cart-flex-item text-right">
                <div class="cart__qty text-center">
                  <div class="qtyField">
                    <a class="qtyBtn minus" href="javascript:void(0);"
                      ><i class="icon icon-minus"></i
                    ></a>
                    <input
                      class="cart__qty-input qty"
                      type="text"
                      name="cart_item-{{ item.pk }}"
                      id="qty"
                      value="{{ item.quantity }}"
                      pattern="[0-9]*"
                    />
                    <a class="qtyBtn plus" href="javascript:void(0);"
                      ><i class="icon icon-plus"></i
                    ></a>
                  </div>
                </div>
              </td>
              <td class="text-right small--hide cart-price">
                <div><span class="money">${{ item.total_price }}</span></div>
              </td>
              <td class="text-center small--hide">
                <a
                  href="#"
                  class="btn btn--secondary cart__remove"
                  title="Remove item"
                  id="removeItem"
                  data-id="{{ item.pk }}"
                  ><i class="icon icon anm anm-times-l"></i
                ></a>
              </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr class="cart__row border-bottom line1 cart-flex border-top">
              <td colspan="6">
                <h3 class="text-center">You have no items in your cart</h3>
              </td>
            </tr>
            {% endif %}

          </tbody>
          <tfoot>
            <tr>
              <td colspan="3" class="text-left">
                <a
                  href="{% url 'products:all_products' %}"
                  class="btn btn-secondary btn--small cart-continue"
                  >Continue shopping</a
                >
              </td>
              <td colspan="3" class="text-right">
                <button
                  type="button"
                  name="clear"
                  class="btn btn-secondary btn--small small--hide" id="clearCart"
                >
                  Clear Cart
                </button>
                <button
                  type="submit"
                  name="update"
                  class="btn btn-secondary btn--small cart-continue ml-2"
                >
                  Update Cart
                </button>
              </td>
            </tr>
          </tfoot>
        </table>
        <div class="currencymsg">We processes all orders in USD. While the content of your cart is currently displayed in USD, the checkout will use USD at the most current exchange rate.</div>

      </form>
    </div>
    
    <div class="col-12 col-sm-12 col-md-4 col-lg-4 cart__footer">
     
        <div class="solid-border w-100">
          <div class="row">
            <span class="col-12 col-sm-6 cart__subtotal-title"><strong>Subtotal</strong></span>
            <span class="col-12 col-sm-6 cart__subtotal-title cart__subtotal text-right"><span class="money">${{ subtotal }}</span></span>
          </div>
          <div class="cart__shipping">Shipping &amp; taxes calculated at checkout</div>
          <div class="cart__shipping">By clicking the button you agree to our terms and conditions</div>
          <a class="btn btn--small-wide checkout w-100 p-3" href="{% url 'products:checkout' %}">Checkout</a>
          <!-- <input type="submit" name="checkout" id="cartCheckout" class="btn btn--small-wide checkout" value="Checkout" disabled="disabled"> -->
          <div class="paymnet-img"><img src="{% static 'images/payment-img.jpg' %}" alt="Payment"></div>
        </div>

    </div>
  </div>
</div>
{% endblock %}

products/templates/products/collections.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}COLLECTIONS{% endblock %}

{% block content %}
<!--Page Title-->
<div class="page section-header text-center">
    <div class="page-title">
        <div class="wrapper">
            <h1 class="page-width">Collections Page</h1>
        </div>
    </div>
</div>
<!--End Page Title-->

<div class="container collection-box">
    <div class="row">
        <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="colletion-item">
                <a href="bags">
                    <img class="blur-up lazyload" data-src="{% static 'images/collection/collection-page1.jpg' %}"
                        src="{% static 'images/collection/collection-page1.jpg' %}" alt="image" title="">
                    <span class="title"><span>Bags</span></span>
                </a>
            </div>
        </div>
        <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="colletion-item">
                <a href="clothing">
                    <img class="blur-up lazyload" data-src="{% static 'images/collection/collection-page2.jpg' %}"
                        src="{% static 'images/collection/collection-page2.jpg' %}" alt="image" title="">
                    <span class="title"><span>Fashion</span></span>
                </a>
            </div>
        </div>
        <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="colletion-item">
                <a href="shoes">
                    <img class="blur-up lazyload" data-src="{% static 'images/collection/collection-page3.jpg' %}"
                        src="{% static 'images/collection/collection-page3.jpg' %}" alt="image" title="">
                    <span class="title"><span>Shoes</span></span>
                </a>
            </div>
        </div>
        <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="colletion-item">
                <a href="accessories">
                    <img class="blur-up lazyload" data-src="{% static 'images/collection/collection-page6.jpg' %}"
                        src="{% static 'images/collection/collection-page6.jpg' %}" alt="image" title="">
                    <span class="title"><span>Accessories</span></span>
                </a>
            </div>
        </div>
        <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="colletion-item">
                <a href="cosmetics">
                    <img class="blur-up lazyload" data-src="{% static 'images/collection/collection-page7.jpg' %}"
                        src="{% static 'images/collection/collection-page7.jpg' %}" alt="image" title="">
                    <span class="title"><span>Cosmetics</span></span>
                </a>
            </div>
        </div>
        <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="colletion-item">
                <a href="jewellery">
                    <img class="blur-up lazyload" data-src="{% static 'images/collection/collection-page8.jpg' %}"
                        src="{% static 'images/collection/collection-page8.jpg' %}" alt="image" title="">
                    <span class="title"><span>Jewellery</span></span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/order_complete.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}THANK YOU{% endblock %}

{% block content %}
<!-- Lookbook Start -->
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">	
            <div class="empty-page-content text-center">
                <h1>Order Received</h1>
                <p>Thank you for shopping with us. You probably will never recieve the products since this is a template site</p>
                <p><a href="{% url 'products:orders' %}" class="btn btn--has-icon-after">View Order &nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
              </div>
        </div>
    </div>
</div>
<!-- Lookbook Start -->
{% endblock %}

products/templates/products/orders.html
{% extends 'main/base.html' %} 
{% load static %} 

{% block title %}ORDERS{% endblock %} 

{% block content %}
<!--Page Title-->
<div class="page section-header text-center">
    <div class="page-title">
        <div class="wrapper"><h1 class="page-width">Your Orders</h1></div>
      </div>
</div>
<!--End Page Title-->

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 main-col">
                <div class="wishlist-table table-content table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="product-price text-center alt-font">Images</th>
                                <th class="product-name alt-font">Product</th>
                                <th class="product-price text-center alt-font">Unit Price</th>
                                <th class="stock-status text-center alt-font">Order Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if order_items %}
                            {% for item in order_items %}
                            <tr>
                                <td class="product-thumbnail text-center">
                                    <a href="{% url 'products:view_product_details' short_name=item.short_name %}">
                                        <img src="{% static '' %}media/{{ item.image }}" alt="" title="" />
                                    </a>
                                </td>
                                <td class="product-name"><h4 class="no-margin"><a href="{% url 'products:view_product_details' short_name=item.short_name %}">{{ item.name }}</a></h4></td>
                                <td class="product-price text-center"><span class="amount">${{ item.price }}</span></td>
                                <td class="stock text-center">
                                    <span class="in-stock">{{ item.status }}</span>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="6">
                                    <h3 class="text-center">You have no orders</h3>
                                </td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
           </div>
    </div>
</div>
{% endblock %}

products/templates/products/wishlist.html
{% extends 'main/base.html' %} 
{% load static %} 

{% block title %}WISHLIST{% endblock %} 

{% block content %}
<!--Page Title-->
<div class="page section-header text-center">
    <div class="page-title">
        <div class="wrapper"><h1 class="page-width">Wish List</h1></div>
      </div>
</div>
<!--End Page Title-->

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 main-col">
                <div class="wishlist-table table-content table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="product-name text-center alt-font">Remove</th>
                                <th class="product-price text-center alt-font">Images</th>
                                <th class="product-name alt-font">Product</th>
                                <th class="product-price text-center alt-font">Unit Price</th>
                                <th class="stock-status text-center alt-font">Stock Status</th>
                                <th class="product-subtotal text-center alt-font">Add to Cart</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if wishlist_items %}
                            {% for item in wishlist_items %}
                            <tr>
                                <td class="product-remove text-center" valign="middle">
                                    <a href="#" data-id="{{ item.pk }}" id="removeWishlist">
                                        <i class="icon icon anm anm-times-l"></i>
                                    </a></td>
                                <td class="product-thumbnail text-center">
                                    <a href="#"><img src="{% static '' %}media/{{ item.image }}" alt="" title="" /></a>
                                </td>
                                <td class="product-name"><h4 class="no-margin"><a href="{% url 'products:view_product_details' short_name=item.short_name %}">{{ item.name }}</a></h4></td>
                                <td class="product-price text-center"><span class="amount">${{ item.price }}</span></td>
                                <td class="stock text-center">
                                    <span class="in-stock">{{ item.stock }}</span>
                                </td>
                                <td class="product-subtotal text-center">
                                    <form action="{% url 'products:add_to_cart' %}?return_url={{ request.path }}" method="post">
                                        {% csrf_token %}
                                        <input type="text" name="pk" value="{{ item.pk }}" hidden>
                                        <button type="submit" class="btn btn-small">Add To Cart</button>
                                    </form>
                                    
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="6">
                                    <h3 class="text-center">You have no items in your wishlist</h3>
                                </td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
           </div>
    </div>
</div>
{% endblock %}